# Config file for Bomberman 64 The Second Attack Recompilation

[input]
entrypoint = 0x80000400
# Paths are relative to the location of this config file.
rom_file_path = "bm64tsa.decomp.us.z64"
bss_section_suffix = "_bss"
symbols_file_path = "BM64TSASyms/dump.toml"
output_func_path = "RecompiledFuncs"
relocatable_sections_path = "bm64tsa.us.overlays.txt"
recomp_include = "#include \"bm64tsa_recomp.h\""
trace_mode = false

[patches]
stubs = [
    "func_80073EC0", # watchlo
    "func_80073EE0", # watchhi, i think
]

ignored = [
    #"__osBlockSum",
    "__osPfsReleasePages",
    "__osPfsDeclearPage",
    #"osPfsReFormat",
]

# These are osGetCount calls, but we cannot recompile that handwritten function, so we patch these to
# call osGetCount instead which is handled on recomp side.
[[patches.instruction]]
func = "func_ovl_boss_demon_43009E60"
vram = 0x43009E64
value = 0x00000000

[[patches.hook]]
func = "func_ovl_boss_demon_43009E60"
before_vram = 0x43009E64
text = """
    osGetCount_recomp(rdram, ctx);
"""

[[patches.instruction]]
func = "func_ovl_boss_devil_4300ADD0"
vram = 0x4300ADD4
value = 0x00000000

[[patches.hook]]
func = "func_ovl_boss_devil_4300ADD0"
before_vram = 0x4300ADD4
text = """
    osGetCount_recomp(rdram, ctx);
"""

[[patches.instruction]]
func = "func_ovl_boss_angel_4300B4A0"
vram = 0x4300B4A4
value = 0x00000000

[[patches.hook]]
func = "func_ovl_boss_angel_4300B4A0"
before_vram = 0x4300B4A4
text = """
    osGetCount_recomp(rdram, ctx);
"""

# The GFX system uses KSEG1 pointers for its GFX pointers: turn these back to KSEG0 so recomp doesnt segfault.
[[patches.instruction]]
func = "func_8000479C" # gfxGetTopPointer
vram = 0x800047CC
value = 0x3C010000 # lui        $at, (0x20000000 >> 16) -> lui        $at, (0x00000000 >> 16)

[[patches.instruction]]
func = "func_800047E0" # gfxGetPointer
vram = 0x80004810
value = 0x3C010000 # lui        $at, (0x20000000 >> 16) -> lui        $at, (0x00000000 >> 16)

# When osAiGetLength returns a number that exceeds the target amount of samples per frame, the calculation (target samples per frame - osAiGetLength()) will result in a negative number.
# When the clamping takes place to prevent a number of bytes that is too small, it doesn't take into account the negative number that resulted from the calculation.
# Not doing this results in a negative number being given to osAiSetNextBuffer causing a massive memory leak and crash (because a signed negative number is being read as unsigned).
[[patches.instruction]]
func = "func_80026578"
vram = 0x80026790
value = 0x00E3082A # sltu $at, $a3, $v1 -> slt $at, $a3, $v1

# Force the widescreen values.
[[patches.hook]]
func = "func_80008738"
before_vram = 0x80008768
text = """
// Patch to force widescreen.
    ctx->r18 = 0; // s2
    ctx->r19 = 0; // s3
    ctx->r20 = 320; // s4
    ctx->r21 = 240; // s5
"""

[[patches.hook]]
func = "func_80008738"
before_vram = 0x8000885C
text = """
    ctx->r24 = 0x005003C0; // force scissor write to store 320, 240 coords. Due to the float rounding, this gets discarded
"""

[[patches.hook]]
func = "func_800082AC"
before_vram = 0x80008494
text = """
    ctx->r13 = 0x005003C0; // force scissor write to store 320, 240 coords. Due to the float rounding, this gets discarded
"""

# Patch the game over fade square coordinates so it's properly stretched by RT64.
[[patches.instruction]]
func = "func_80031260"
vram = 0x8003134C
value = 0x240E0140 # addiu      $t6, $zero, 0x130 -> addiu      $t6, $zero, 0x140

[[patches.instruction]]
func = "func_80031260"
vram = 0x80031350
value = 0x240F00F0 # addiu      $t7, $zero, 0xE0 -> addiu      $t7, $zero, 0xF0

# We also need to override the actual DL write because of the float rounding done on these values.
[[patches.hook]]
func = "func_80030BB4"
before_vram = 0x80030D08
text = """
    // only patch if the game over fade
    if (ctx->r15 == 0xF64DC39C) {
        ctx->r15 = 0xF65003C0;
    }
"""

[[patches.hook]]
func = "func_80030BB4"
before_vram = 0x80030D68
text = """
    // only patch if the game over fade
    if (ctx->r15 == 0x00020020) {
        ctx->r15 = 0x00000000;
    }
"""
